### ISSUE TITLE
Feedback

### ISSUE THREAD

**Issue by GrosSacASac** [tamb/domponent#17]
I am working on a similar thing called [dom99](https://github.com/GrosSacASac/DOM99/) The docs are a bit out of date, but check the examples.

After skimming through your project:

data-state

You basically evented yet another data format, consider instead using something native of the platform like

data-state="{count:24, isEven:true}"

or

data-state-count="24" data-state-isEven="true"

data-key

it is optional, must be unique , but what does it do ?

Component Fields

why prefix things with $ ?

do not commit  	domponent-1.0.0-alpha.18.tgz

Otherwise very interesting project, I give more detailed feedback later

**Comment by tamb** [comment]
@GrosSacASac That's great feedback!  I'm gonna rewrite the data format to accept objects.    I'll also explain the `data-key` portion better.  It's used when passing props.  I prefixed the Component fields with `$` so it would be super super clear what was from the library.  Maybe I don't need `$`??  I'm totally not attached to it and could easily remove it.  Thanks for the feedback!

**Comment by tamb** [comment]
I'm gonna mark this as closed and return to the possibility of removing the `$` from Component fields.
